spring:
    cloud:
        openfeign:
            client:
                config:
                    default:
                        logger-level: FULL


server:
    port: 8081

logging:
    level:
        org:
            springframework:
                web: DEBUG

